apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  NEXT_TELEMETRY_DISABLED: {{ .Values.env.NEXT_TELEMETRY_DISABLED | quote }}
  NEXT_PUBLIC_GRAPHQL_URL: {{ .Values.env.NEXT_PUBLIC_GRAPHQL_URL | quote }}
